name: Test Action
on:	[push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Resumes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            tex/Resume_academic.tex
            tex/Resume_professional.tex
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: tex/
          path: tex/
        if: always()
