name: Test Action
on:	[push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Resumes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Resume_academic.tex
            Resume_professional.tex
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: ./
        if: always()
