name: Created CV
on:	[push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Resumes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Resume_academic.tex
            Resume_professional.tex
      - name: Upload Academic CV
        uses: actions/upload-artifact@master
        with:
          name: academic.pdf
          path: ./Resume_academic.pdf
        if: always()
      - name: Upload Professional CV
        uses: actions/upload-artifact@master
        with:
          name: professional.pdf
          path: ./Resume_professional.pdf
        if: always()
      - name: upload to CV branch
        run: git checkout -b CVs; git add Resume_*.pdf; git config user.email "akshayantimatter@gmail.com"; git config user.name "CV Writer"; git commit -m "Updated CVs"; git show-ref; git push -u origin CVs;
